baseURL: https://www.smsurvey.app/
languageCode: en-us
title: Short Message Survey
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: Short Message Survey offers assistance for researches with gathering
      intensive longitudinal data via text message.
    meta_og_description: Short Message Survey offers assistance for researches with gathering
      intensive longitudinal data via text message.
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png
    meta_og_title: Hugo Hero Theme
    meta_og_type: website
    meta_og_url: https://hugo-hero.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  logo:
    alt: Hugo Hero
    desktop: images/logo.svg
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/logo-mobile.svg
    mobile_height: 36px
    mobile_width: 36px
menu:
  main:
    - name: Services
      url: /services/
      weight: 1
    - name: Work
      url: /work/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: History
      url: /history/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
